version: "3"

services:
  reader:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.uds
    environment:
      - PORT=8080
      - PROXY_IMAGES=1
    volumes:
      - ./sockets:/sockets/
    restart: unless-stopped
