FROM node:20-alpine3.18

COPY --from=caddy:latest /usr/bin/caddy /usr/bin/caddy

WORKDIR /app

COPY . .
COPY Caddyfile / 
COPY run.sh /

RUN npm i

ENTRYPOINT [  ]

RUN chmod +x /run.sh

CMD [ "/run.sh" ]